### ISSUE TITLE
How to serialise table?

### ISSUE THREAD

**Issue by tomkiss** [jasonphillips/slate-deep-table#3]
Hi,

THANK YOU for adding thead support in this release, really much appreciated.

I'm struggling to use this within a serialiser, as I'm finding the `tbody` and `thead` tags being stripped out. Is there a recommended method for this?

I'm using a fairly standard implementation of the seraliser as [seen in the docs](https://docs.slatejs.org/walkthroughs/saving-and-loading-html-content).

Here's an (abridged) version:

```
const rules = [
  {
    deserialize(el, next) {
      const type = BLOCK_TAGS[el.tagName.toLowerCase()]
      if (type) {
        return {
          object: 'block',
          type: type,
          nodes: next(el.childNodes),
        }
      }
    },
    serialize(obj, children) {
      if (obj.object == 'block') {
        switch (obj.type) {
            case 'table': return (<table>{children}</table>);
            case 'table_row':   return (<tr>{children}</tr>);
            case 'table_cell':  return (<td>{children}</td>);
[...]
        }
      }
    },
  }
];
```
Something like the above will strip out the `thead` and `tbody`, and if I add cases for them in the `switch` statement, they're not ever seen by the seralizer.

I appreciate this isn't a support forum, so I understand if you remove this issue, although any pointers appreciated :)

**Comment by jasonphillips** [comment]
Apologies for missing this issue for ages. I added a test just now that shows how to serialize with `thead` / `tbody`, and that verifies it works correctly.

Check out this file:  https://github.com/jasonphillips/slate-deep-table/blob/master/tests/serialize.js

Basically you just need to check to see if the table has `headless` set true in its data, and otherwise split the header row from the others. This could be added to the library itself... I mainly didn't think of that since I was following the conventions of other slate libs, and hadn't noticed them exporting a serializer. It makes a lot of sense though.

**Comment by jasonphillips** [comment]
For information on the default serializers now included:

https://github.com/jasonphillips/slate-deep-table/issues/18
